/**
 * Reads the Vite-built single-file HTML from web/dist/index.html
 * and generates src/generated/dashboard-html.ts exporting it as a string constant.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const distPath = join(import.meta.dir, "..", "web", "dist", "index.html");
const outDir = join(import.meta.dir, "..", "src", "generated");
const outPath = join(outDir, "dashboard-html.ts");

const html = readFileSync(distPath, "utf-8");

mkdirSync(outDir, { recursive: true });

const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  outPath,
  `// Auto-generated by scripts/embed-dashboard.ts — do not edit\nexport const DASHBOARD_HTML = \`${escaped}\`;\n`
);

console.log(`Generated ${outPath} (${html.length} bytes)`);
